extends:
  - pegasus

plugins:
  - angular

overrides:
  - files:
      - '!src/*'
      - '!docs/*'
    extends:
      - pegasus/node
    rules:
      no-console: off
      
globals:
  angular: true

env:
  jasmine: true
  angular/mocks: true
